name: github_ci
on:
  push:
    branches: [ "master" ]
  pull_request: 
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout the repository
      uses: actions/checkout@v4

    - name: install java8
      uses: actions/setup-java@v4
      with: 
        java-version: '8'
        distribution: 'temurin'
        cache: 'maven'

    - name: build the code with maven and generate a package
      run: mvn clean package
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: ./gameoflife-web/target/*.war

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    # - name: building the docker image
    #   run: |
    #     docker build -t mytomcat:$GITHUB_SHA ./gameoflife-web
    #     docker images
    #   shell: bash
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./gameoflife-web
        push: true
        tags: mani5a3/github-action-tomcat-war:latest